version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies--{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run: yarn lint

  publish:
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run: 
          name: Login into Expo
          command: yarn -s run expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run: 
          name: Publish to Expo
          command: yarn -s run expo publish --non-interactive --max-workers 1 -- release-channel $EXPO_RELEASE_CHANNEL

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - test