platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: "ios/partyclient.xcodeproj")
    build_app(workspace: "ios/partyclient.xcworkspace", scheme: "partyclient", output_directory: "ios")
  end
end
