platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: "ios/party-stg.xcodeproj")
    build_app(workspace: "ios/partyclient.xcworkspace", scheme: "party-stg", output_directory: "ios")
  end
end
